# Generated by Django 3.0.8 on 2020-09-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200918_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='Ap_Notes',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
